### ISSUE TITLE
TypeError: Cannot set property 'show' of undefined

### ISSUE THREAD

**Issue by YoginthS** [VotePen/Platform#102]
https://sentry.io/votepen/website/issues/489663769/

```
TypeError: Cannot set property 'show' of undefined
  at call (./resources/assets/js/vue-codes.js:194:41)
  at call (./resources/assets/js/mixins/Helpers.js:107:28)
  at apply (./resources/assets/js/mixins/Submission.js:201:26)
...
(8 additional frame(s) were not displayed)
```

**Comment by YoginthS** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/VotePen/Platform/issues/4 (TypeError: Cannot read property 'channels' of undefined), https://github.com/VotePen/Platform/issues/96 (TypeError: Cannot read property 'length' of undefined), https://github.com/VotePen/Platform/issues/69 (TypeError: Cannot read property 'upVotes' of undefined), https://github.com/VotePen/Platform/issues/98 (TypeError: Cannot read property 'users' of undefined), and https://github.com/VotePen/Platform/issues/97 (TypeError: Cannot read property 'submissions' of undefined).

**Comment by YoginthS** [comment]
will fix it!
