### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by HaroenViaene** [votepen/platform#12]
https://sentry.io/votepen/votepen/issues/413152708/

    TypeError: Cannot read property 'length' of null
      at Be.<anonymous> (/js/app.js:1:1)
      at n (/js/vendor.js:1:1)
      at t (/js/app.js:1:1)
      at Array.forEach (<anonymous>)
      at apply (/js/app.js:1:1)
    ...
    (1 additional frame(s) were not displayed)
    
    TypeError: Cannot read property 'length' of null

**Comment by yoginth** [comment]
**Thanks**, The issue has been fixed already!
