### ISSUE TITLE
TypeError: Cannot read property 'submissions' of undefined

### ISSUE THREAD

**Issue by YoginthS** [VotePen/Platform#97]
https://sentry.io/votepen/website/issues/489629033/

```
TypeError: Cannot read property 'submissions' of undefined
  at call (./resources/assets/js/mixins/Submission.js:77:46)
  at apply (./resources/assets/js/mixins/Submission.js:255:41)
  at apply (./resources/assets/js/components/submission/LinkSubmission.vue?f3e0:1:2355)
  at apply (./resources/assets/js/components/SubmissionFooter.vue?9146:1:787)
...
(13 additional frame(s) were not displayed)
```

**Comment by YoginthS** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by YoginthS** [comment]
will fix it!
